apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks-8bd8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks-8bd8"
  template:
    metadata:
      labels:
        app: "myaks-8bd8"
    spec:
      containers:
        - name: "myaks-8bd8"
          image: "containerflaskapp.azurecr.io/myaks"
          ports:
          - containerPort: 8080