on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerflaskapp.azurecr.io
        username: ${{ secrets.acr_containerflaskapp_username }}
        password: ${{ secrets.acr_containerflaskapp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t containerflaskapp.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push containerflaskapp.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksa86a | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksa86a`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksa86a
        container-registry-url: containerflaskapp.azurecr.io
        container-registry-username: ${{ secrets.acr_containerflaskapp_username }}
        container-registry-password: ${{ secrets.acr_containerflaskapp_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksa86a
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerflaskapp.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth
